inherit_from: .rubocop_todo.yml

AllCops:
# 除外するディレクトリ（自動生成されたファイル）
# デフォルト設定にある"vendor/**/*"が無効化されないように記述
 Exclude:
   - "vendor/**/*" # rubocop config/default.yml
   - "db/**/*"
   - "config/**/*"
   - "bin/*"
   - "node_modules/**/*"
   - "Gemfile"


# 1行あたりの文字数をチェックする
Layout/LineLength:
 Max: 130
# 下記ファイルはチェックの対象から外す
 Exclude:
   - "Rakefile"
   - "spec/rails_helper.rb"
   - "spec/spec_helper.rb"

# RSpecは1つのブロックあたりの行数が多くなるため、チェックの除外から外す
# ブロック内の行数をチェックする
Metrics/BlockLength:
 Exclude:
   - "spec/**/*"

# Assignment: 変数への代入
# Branch: メソッド呼び出し
# Condition: 条件文
# 上記項目をRubocopが計算して基準値を超えると警告を出す（上記頭文字をとって'Abc'）
Metrics/AbcSize:
 Max: 50

# メソッドの中身が複雑になっていないか、Rubocopが計算して基準値を超えると警告を出す
Metrics/PerceivedComplexity:
 Max: 8

# 循環的複雑度が高すぎないかをチェック（ifやforなどを1メソッド内で使いすぎている）
Metrics/CyclomaticComplexity:
 Max: 10

# メソッドの行数が多すぎないかをチェック
Metrics/MethodLength:
 Max: 30

# ネストが深すぎないかをチェック（if文のネストもチェック）
Metrics/BlockNesting:
 Max: 5

# クラスの行数をチェック（無効）
Metrics/ClassLength:
 Enabled: false

# 空メソッドの場合に、1行のスタイルにしない　NG例：def style1; end
Style/EmptyMethod:
 EnforcedStyle: expanded

# クラス内にクラスが定義されていないかチェック（無効）
Style/ClassAndModuleChildren:
 Enabled: false

# 日本語でのコメントを許可
Style/AsciiComments:
 Enabled: false

# クラスやモジュール定義前に、それらの説明書きがあるかをチェック（無効）
Style/Documentation:
 Enabled: false

# ％i（）構文を使用していないシンボルで構成される配列リテラルをチェック（無効）
Style/SymbolArray:
 Enabled: false

# 文字列に値が代入されて変わっていないかチェック（無効）
Style/FrozenStringLiteralComment:
 Enabled: false

# メソッドパラメータ名の最小文字数を設定
Naming/MethodParameterName:
 MinNameLength: 1

# 以下は追記しました。消しても良いです。

 # 新しい cops を無効に設定
Gemspec/AddRuntimeDependency:
  Enabled: false
Gemspec/DeprecatedAttributeAssignment:
  Enabled: false
Gemspec/DevelopmentDependencies:
  Enabled: false
Gemspec/RequireMFA:
  Enabled: false
Layout/LineContinuationLeadingSpace:
  Enabled: false
Layout/LineContinuationSpacing:
  Enabled: false
Layout/LineEndStringConcatenationIndentation:
  Enabled: false
Layout/SpaceBeforeBrackets:
  Enabled: false
Lint/AmbiguousAssignment:
  Enabled: false
Lint/AmbiguousOperatorPrecedence:
  Enabled: false
Lint/AmbiguousRange:
  Enabled: false
Lint/ConstantOverwrittenInRescue:
  Enabled: false
Lint/DeprecatedConstants:
  Enabled: false
Lint/DuplicateBranch:
  Enabled: false
Lint/DuplicateMagicComment:
  Enabled: false
Lint/DuplicateMatchPattern:
  Enabled: false
Lint/DuplicateRegexpCharacterClassElement:
  Enabled: false
Lint/EmptyBlock:
  Enabled: false
Lint/EmptyClass:
  Enabled: false
Lint/EmptyInPattern:
  Enabled: false
Lint/IncompatibleIoSelectWithFiberScheduler:
  Enabled: false
Lint/ItWithoutArgumentsInBlock:
  Enabled: false
Lint/LambdaWithoutLiteralBlock:
  Enabled: false
Lint/LiteralAssignmentInCondition:
  Enabled: false
Lint/MixedCaseRange:
  Enabled: false
Lint/NoReturnInBeginEndBlocks:
  Enabled: false
Lint/NonAtomicFileOperation:
  Enabled: false
Lint/NumberedParameterAssignment:
  Enabled: false
Lint/OrAssignmentToConstant:
  Enabled: false
Lint/RedundantDirGlobSort:
  Enabled: false
Lint/RedundantRegexpQuantifiers:
  Enabled: false
Lint/RefinementImportMethods:
  Enabled: false
Lint/RequireRangeParentheses:
  Enabled: false
Lint/RequireRelativeSelfPath:
  Enabled: false
Lint/SymbolConversion:
  Enabled: false
Lint/ToEnumArguments:
  Enabled: false
Lint/TripleQuotes:
  Enabled: false
Lint/UnexpectedBlockArity:
  Enabled: false
Lint/UnmodifiedReduceAccumulator:
  Enabled: false
Lint/UselessRescue:
  Enabled: false
Lint/UselessRuby2Keywords:
  Enabled: false
Metrics/CollectionLiteralLength:
  Enabled: false
Naming/BlockForwarding:
  Enabled: false
Security/CompoundHash:
  Enabled: false
Security/IoMethods:
  Enabled: false
Style/ArgumentsForwarding:
  Enabled: false
Style/ArrayIntersect:
  Enabled: false
Style/CollectionCompact:
  Enabled: false
Style/ComparableClamp:
  Enabled: false
Style/ConcatArrayLiterals:
  Enabled: false
Style/DataInheritance:
  Enabled: false
Style/DirEmpty:
  Enabled: false
Style/DocumentDynamicEvalDefinition:
  Enabled: false
Style/EmptyHeredoc:
  Enabled: false
Style/EndlessMethod:
  Enabled: false
Style/EnvHome:
  Enabled: false
Style/ExactRegexpMatch:
  Enabled: false
Style/FetchEnvVar:
  Enabled: false
Style/FileEmpty:
  Enabled: false
Style/FileRead:
  Enabled: false
Style/FileWrite:
  Enabled: false
Style/HashConversion:
  Enabled: false
Style/HashExcept:
  Enabled: false
Style/IfWithBooleanLiteralBranches:
  Enabled: false
Style/InPatternThen:
  Enabled: false
Style/MagicCommentFormat:
  Enabled: false
Style/MapCompactWithConditionalBlock:
  Enabled: false
Style/MapIntoArray:
  Enabled: false
Style/MapToHash:
  Enabled: false
Style/MapToSet:
  Enabled: false
Style/MinMaxComparison:
  Enabled: false
Style/MultilineInPatternThen:
  Enabled: false
Style/NegatedIfElseCondition:
  Enabled: false
Style/NestedFileDirname:
  Enabled: false
Style/NilLambda:
  Enabled: false
Style/NumberedParameters:
  Enabled: false
Style/NumberedParametersLimit:
  Enabled: false
Style/ObjectThen:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/OperatorMethodCall:
  Enabled: false
Style/QuotedSymbols:
  Enabled: false
Style/RedundantArgument:
  Enabled: false
Style/RedundantArrayConstructor:
  Enabled: false
Style/RedundantConstantBase:
  Enabled: false
Style/RedundantCurrentDirectoryInPath:
  Enabled: false
Style/RedundantDoubleSplatHashBraces:
  Enabled: false
Style/RedundantEach:
  Enabled: false
Style/RedundantFilterChain:
  Enabled: false
Style/RedundantHeredocDelimiterQuotes:
  Enabled: false
Style/RedundantInitialize:
  Enabled: false
Style/RedundantLineContinuation:
  Enabled: false
Style/RedundantRegexpArgument:
  Enabled: false
Style/RedundantRegexpConstructor:
  Enabled: false
Style/RedundantSelfAssignmentBranch:
  Enabled: false
Style/RedundantStringEscape:
  Enabled: false
Style/ReturnNilInPredicateMethodDefinition:
  Enabled: false
Style/SelectByRegexp:
  Enabled: false
Style/SendWithLiteralMethodName:
  Enabled: false
Style/SingleLineDoEndBlock:
  Enabled: false
Style/StringChars:
  Enabled: false
Style/SuperArguments:
  Enabled: false
Style/SuperWithArgsParentheses:
  Enabled: false
Style/SwapValues:
  Enabled: false
Style/YAMLFileRead:
  Enabled: false
